### PR TITLE
Support record type and repeated mode for list table data

### PR DESCRIPTION
**Pull request by kysnm**
It was implemented to be recursively solved.

### CODE REVIEW

**Comment by sonots** [comment]
LGTM

**Comment by sonots** [comment]
You can merge by yourself now!

**Comment by kysnm** [comment]
I guess I'll need to add a description about the changes in the Changelog. Do I add it to the same PR?

**Comment by sonots** [comment]
Either of same PR or another PR is fine, but you may send another PR to release a new gem version including ChangeLog.

**Comment by kysnm** [comment]
I see.

I will merge this PR.
And I will send another PR to release a new gem version.

**Pull request merged**
